select * from customer limit 10;

-- Q1. what is total revenue generated by male or female.
select gender,sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2. which customer used a discount but still spent more than the average purchase amount
select customer_id,purchase_amount
from customer 
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. which are the top 5 products with the highest review rating.
select item_purchased , Round(avg(cast(review_rating as decimal (10,2))),2) as "Averege product Rating"
from customer
group by item_purchased
order by  Round(avg(cast(review_rating as decimal (10,2))),2) desc
limit 5;

-- Q4.Do subscribed customer spend more? Compare average total and revenue between subscriber or non subscribers.
select subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by avg_spend,total_revenue desc;

-- Q5. Which product have the highest percentage of purchases with discounts applied?
select item_purchased,
Round(100 *sum(case when discount_applied = "Yes" then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q6. segemnt customer into new,returing,and loyel based on their total number of previous purchase ,and show 
-- the count of each segments.
with customer_type as(
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "Returning"
    else "Loyel"
    end as customer_segment 
from customer
)

select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q7. what are the top 3 most purchased products with in the each category.
with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category,item_purchased
)

select item_rank,item_purchased,category,total_orders
from item_counts
where item_rank <= 3;

-- Q8.Are customers who are repeat buyer (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyer
from customer
where previous_purchases > 5
group by subscription_status;

-- Q9. what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;





    







